AllCops:
  TargetRubyVersion: 2.2.3
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'

Metrics/LineLength:
  Max: 110

Style/SingleLineBlockParams:
  Enabled: false

# Style/SpaceInsideHashLiteralBraces:
#   EnforcedStyle: space
#   EnforcedStyleForEmptyBraces: no_space
#   SupportedStyles:
#     - space
#     - no_space
