#!/usr/bin/env bash

echo 'Backing up package lists'
/bin/ls ~/.atom/packages | grep -v READ > ~/.atom/package-list
/bin/ls /usr/local/lib/node_modules > ~/.dotfiles/.node_modules

if [[ `uname` == 'Darwin' ]]; then
  echo 'Backup up OSX specific package lists...'
  /bin/ls /usr/local/Cellar > ~/.dotfiles/.cellar
  /bin/ls /opt/homebrew-cask/Caskroom > ~/.dotfiles/.casks
fi

