#!/bin/bash -e

dir=`pwd`

symlink () {
	for dotfile; do
		# echo "Running: ln -sf $dir/$dotfile $HOME"
		echo "Symlinking $dotfile"
		ln -sf $dir/$dotfile $HOME
	done
}

files=( 
	'.rspec'
	'.tmux*'
	'.zshrc'
	'.gitignore_global'
	'.gitconfig'
	'.git_template'
	'.agignore'
	'.rubocop.yml'
	'.gnupg'
)
symlink ${files[@]}


read -p "Link neovim dotfiles? [Y/n] " confirm
if [ -z $confirm ] || [ $confirm = 'y' ]; then
	echo 'Linking Neovim'
	ln -sf $dir/.config/nvim $HOME/.config/
	curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi


if [[ $(uname) = 'Linux' ]]; then
	linux_files=('.scripts' '.fonts' '.Xresources')
	symlink ${linux_files[@]}

	read -p "Install Linux Essentials? [Y/n] " confirm
	if [ -z $confirm ] || [ $confirm = 'y' ]; then
		echo 'Installing Linux essentals...'
		sudo apt-get -y install cmake ctags curl git openvpn p7zip-full pass \
			pinentry-curses screenfetch scrot silversearcher-ag tmux tree \
			tty-clock xbacklight xcape xclip zsh 
	fi

	read -p "Symlink i3 Files [Y/n]" confirm
	if [ -z $confirm ] || [ $confirm = 'y' ]; then
		i3_files=('.config/i3/.i3blocks.conf' '.config/i3/.compton.conf')
		symlink ${i3_files[@]}

		ln -sf $dir/.config/i3 $HOME/.config/
		ln -sf $dir/.config/rofi $HOME/.config/
		ln -sf $dir/.config/i3/.i3blocks.conf $HOME/
		ln -sf $dir/.config/i3/.compton.conf $HOME/
	fi

fi


if [[ $(uname) = 'Darwin' ]]; then
	#install homebrew
	$(which brew &> /dev/null) && /usr/bin/ruby \
		-e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

	# install the essentials
	brew tap caskroom/fonts
	brew install zsh git tmux ctags curl the_silver_searcher

	read -p "Install hammerspoon? [Y/n]" confirm
	if [ -z $confirm ] || [ $confirm = 'y' ]; then
		echo 'Intsalling hammerspoon...'
		brew cask install hammerspoon
		symlink '.hammerspoon'
	fi
fi


# fetch submodules
git submodule update --init --recursive


# TODO automate these so they're not necesary
echo 'POST-INSTALL TODOs'
echo
# updates /etc/hosts for ad blocking
echo "If you'd like to install ad-blocking hosts file, run:" 
echo "sudo curl http://winhelp2002.mvps.org/hosts.txt > /etc/hosts"

echo
echo 'Install the rbenv CTags generator'
echo '  - https://github.com/tpope/rbenv-ctags'
echo
echo 'Install Bundler's CTags generator
echo '  - https://github.com/tpope/vim-bundler'
echo
echo "Don't forget to restore additional packages with:"
echo '> cat .cellar | xargs brew install'
echo '> cat .casks | xargs brew cask install'
echo '> cat .node_modules | xargs npm -g install'
