#!/usr/bin/env bash -e

files=( '.vim*' '.rspec' '.tmux*' '.zshrc' '.gitignore_global' '.gitconfig' '.git_template' )
dir=`pwd`

symlink () {
  for dotfile; do
    # echo "Running: ln -sf $dir/$dotfile $HOME"
    echo "Symlinking $dotfile"
    `ln -sf $dir/$dotfile $HOME`
  done
}

symlink ${files[@]}

if ! [[ -e '.installed' ]]; then
  # install homebrew
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  # install the essentials
  brew install zsh git tmux vim

  # install oh-my-zsh
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

  # fetch submodules
  git submodule update --init --recursive

  # install vim plugins
  vim +PluginInstall +qall

  # set installation file so certain commands are skipped on the next run
  touch .installed

  # TODO automate these so they're not necesary
  echo 'POST-INSTALL TODOs'
  echo 'Install the rbenv CTags generator'
  echo '  - https://github.com/tpope/rbenv-ctags'
  echo 'Install Bundler's CTags generator
  echo '  - https://github.com/tpope/vim-bundler'
  echo ''
  echo "Don't forget to restore additional packages with:"
  echo '> cat .cellar | xargs brew install'
  echo '> cat .casks | xargs brew cask install'
  echo '> cat .node_modules | xargs npm -g install'
fi
